cache:
  key: '$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG rebuild4'
  paths:
    - node_modules/

stages:
  - build
  - deploy

release_job:
  image: trion/ng-cli
  stage: build
  before_script:
    - npm install
  script: npm run build:elements:pricing-calculator-cushions
  artifacts:
    name: "project-dev-$CI_COMMIT_REF_NAME"
    paths:
      - elements/pricing-calculator-cushions.js
  only:
    - tags

deploy_prod:
  stage: deploy
  image: cytopia/ansible:latest-tools
  dependencies:
    - release_job
  only:
    - "tags"
  before_script:
    - "[ ! -z \"${PROD_SERVER_PRIVATE_KEY}\" ]"
    - "[ ! -z \"${PROD_SERVER_IP}\" ]"
    - apk add rsync
    - mkdir -p ~/.ssh
    - echo "$PROD_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $PROD_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - mkdir deploy/roles/pricing_calculator/files
    - mv elements/pricing-calculator-cushions.js deploy/roles/pricing_calculator/files/pricing-calculator-cushions.js
    - ansible-playbook -i $PROD_SERVER_IP',' deploy/deploy.yml
