cache:
  key: '$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG rebuild4'
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_image_pricing_calculator:
  stage: build
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD https://nexus-docker.stackr.de
    - docker build -f PricingCalculatorDockerfile  -t nexus-docker.stackr.de/jlc/pricing-calculator .
    - docker push nexus-docker.stackr.de/jlc/pricing-calculator
  only:
    - main
    - master

deploy_service_pricing_calculator:
  stage: deploy
  script:
    - curl -XPOST $SERVICE_WEBHOOK
  only:
    - main
    - master
